# Generated by Django 3.0.4 on 2020-03-13 15:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Qwestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=555, verbose_name='Вопрос')),
                ('input', models.CharField(choices=[('ch', 'checkbox'), ('rd', 'radio')], default='ch', max_length=2, verbose_name='Тип поля')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='TestBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Наименование теста')),
                ('timedelta', models.IntegerField(default=0, verbose_name='Время выполнения теста')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name=' Автор')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=555, verbose_name='Ответ')),
                ('truefild', models.BooleanField(default=False, verbose_name='Правильный ответ')),
                ('qwestion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qwestion.Qwestion', verbose_name='Вопрос')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
