# Generated by Django 3.0.4 on 2020-03-14 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qwestion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='qwestion',
            name='testname',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='qwestion.TestBase', verbose_name='Наименование теста'),
            preserve_default=False,
        ),
    ]
