# Generated by Django 3.0.4 on 2020-03-14 09:17

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('qwestion', '0002_qwestion_testname'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TestBase',
            new_name='Survey',
        ),
        migrations.RenameField(
            model_name='qwestion',
            old_name='testname',
            new_name='survey',
        ),
    ]
