# Generated by Django 3.0.4 on 2020-03-14 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qwestion', '0003_auto_20200314_1217'),
    ]

    operations = [
        migrations.CreateModel(
            name='Raring',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=55)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('ansver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qwestion.Answer')),
            ],
            options={
                'ordering': ['username', '-created'],
            },
        ),
    ]
