# Generated by Django 3.0.4 on 2020-03-15 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qwestion', '0004_raring'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(db_index=True, max_length=55)),
                ('sessionid', models.CharField(db_index=True, max_length=40)),
                ('answer', models.CharField(max_length=10)),
                ('true_answer', models.CharField(max_length=10)),
                ('result', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('qwestion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='qwestion.Qwestion')),
            ],
            options={
                'ordering': ['sessionid', '-created'],
            },
        ),
        migrations.DeleteModel(
            name='Raring',
        ),
    ]
