# Generated by Django 3.0.4 on 2020-03-15 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qwestion', '0005_auto_20200315_1106'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='public',
            field=models.BooleanField(default=False, verbose_name='Опубликовано'),
        ),
    ]
