# Generated by Django 3.0.4 on 2020-03-15 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qwestion', '0006_survey_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='survey',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='qwestion.Survey'),
            preserve_default=False,
        ),
    ]
