# Generated by Django 3.0.4 on 2020-03-16 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qwestion', '0007_rating_survey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='sessionid',
            field=models.CharField(db_index=True, max_length=90),
        ),
    ]
