# Generated by Django 3.0.4 on 2020-03-17 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qwestion', '0008_auto_20200316_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='sessionid',
            field=models.CharField(db_index=True, max_length=200),
        ),
    ]
