# Generated by Django 3.0.4 on 2020-03-26 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qwestion', '0009_auto_20200317_2018'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='email',
            field=models.CharField(blank=True, max_length=55, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='answer',
            field=models.CharField(max_length=10, verbose_name='Список номеров ответов пользователя'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата ответа'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='qwestion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='qwestion.Qwestion', verbose_name='Вопрос'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='result',
            field=models.BooleanField(default=False, verbose_name='Рузельтат'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='qwestion.Survey', verbose_name='Наменование теста'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='true_answer',
            field=models.CharField(max_length=10, verbose_name='Список номеров правильных ответов'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='username',
            field=models.CharField(db_index=True, max_length=55, verbose_name='Имя пользователя'),
        ),
    ]
